### ISSUE TITLE
Opens only origin remote URL, not actually checked out fork

### ISSUE THREAD

**Issue by janpio** [ziyasal/vscode-open-in-github#64]
I have a project that has both the origin/master (local: origin) and a fork/master (local: master) checked out. Although master is the active branch in my project, it opens the URL of origin in the browser.

Am I missing something or is this not supported?

**Comment by danseethaler** [comment]
Yeah looks like it's just hard coded to use origin [here](https://github.com/ziyasal/vscode-open-in-github/blob/41ef1964c4225f7fe9070c36c44913a131d29e61/src/extension.js#L28). I'd like to change this as well since I have many repos without an `origin` at all. I'll try to take a look over the weekend and see if I can add that feature.

**Comment by janpio** [comment]
Although your commit was reverted @danseethaler this now seems to be working. 🤷‍♂️
